name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn run build
